### ISSUE TITLE
change seamless-immutable with immutability-helper

### ISSUE THREAD

**Issue by mstrk** [Cloudoki/react-redux-donderstarter#15]
@cbalves suggested that [seamless-immutable](https://github.com/rtfeldman/seamless-immutable) is a bit confusing and creates problems when we have to update nested data. So I suggest we switch it with [immutability-helper](https://github.com/kolodny/immutability-helper), we have used this one in other projects and is very simple to use. It does not enforce immutability nevertheless, we have to agree to always use this method when changing state to prevent mutability problems.

**Comment by Muffles** [comment]
+1

**Comment by cbalves** [comment]
+1
